# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: obst blog
email: leejihun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  행복한 개발자
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: obst2580@yahoo.co.kr
github_username:  obst2580

# Build settings
markdown: kramdown
